In [1]:
import torch
import torch.nn as nn
from torch.optim import Adam
from torch.utils.data import Dataset,DataLoader
from torchsummary import summary
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

device='cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
data_df=pd.read_csv('processed_vulcan_gesture_data.csv')
data_df.dropna(inplace=True)
data_df.drop(['label'],axis=1,inplace=True)
data_df.drop(data_df.columns[0:3],axis=1,inplace=True)
data_df.head()

         x2        y2        z2  ...       x21       y21       z21
0  0.301471 -0.116610 -0.129769  ... -0.182843 -1.658963 -0.498779
1  0.310695 -0.097785 -0.143740  ... -0.148426 -1.671955 -0.548812
2  0.298582 -0.127836 -0.136238  ... -0.314884 -1.599180 -0.398628
3  0.291528 -0.112419 -0.165270  ... -0.334747 -1.591777 -0.377276
4  0.276684 -0.138026 -0.128775  ... -0.318585 -1.530783 -0.270657

[5 rows x 60 columns]

In [9]:
d_copy=data_df.copy()
for column in data_df.columns:
    data_df[column]=data_df[column]/data_df[column].abs().max()
data_df.head()

         x2        y2        z2  ...       x21       y21       z21
0  0.970314 -0.844837 -0.785191  ... -0.546214 -0.992230 -0.908834
1  1.000000 -0.708455 -0.869725  ... -0.443398 -1.000000 -1.000000
2  0.961014 -0.926172 -0.824334  ... -0.940663 -0.956473 -0.726347
3  0.938309 -0.814474 -1.000000  ... -1.000000 -0.952045 -0.687441
4  0.890533 -1.000000 -0.779178  ... -0.951720 -0.915565 -0.493168

[5 rows x 60 columns]